apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: shop-back
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - shop-back.k8s.kakuom.com
      secretName: shop-back-tls-cert
  rules:
    - host: shop-back.k8s.kakuom.com
      http:
        paths:
          - path: /
            backend:
              serviceName: shop-back
              servicePort: 8080
